env:
  es2021: true
  node: true
  browser: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: off,
  import/extensions: [ "error", "ignorePackages", { "js": "always" } ],
  no-param-reassign: 0
}
